apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000